# Cows And Bulls
# Exercise 18
#
# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that
# the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed
# correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows”
# and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the
# number of guesses the user makes throughout teh game and tell the user at the end.
#
# Say the number generated by the computer is 1138. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 0 bull
#   ...
# Until the user guesses the number.

import random
import string


def rand_num(num_length=4, num_sample=string.digits):
    return "".join(random.sample(num_sample, num_length))


def compare_numbers(a, b):
    cows = 0
    bulls = 0
    cows_list = []
    bulls_list = []

    for i, j in zip(a, b):
        if i == j:
            cows += 1
            cows_list.append(i)

    for i in a:
        if i in b and i not in cows_list and i not in bulls_list:
            bulls += 1
            bulls_list.append(i)

    plural_cow_noun = "cow"
    if cows != 1:
        plural_cow_noun = "cows"
    plural_bull_noun = "bull"
    if bulls != 1:
        plural_bull_noun = "bulls"

    print(a, "Has", cows, plural_cow_noun, "and", bulls, plural_bull_noun)
    # print(cows_list, bulls_list)  # for testing


def cows_and_bulls():
    guesses = 0

    game_number = rand_num()
    # print(game_number)  # for testing
    users_guess = str(input("Welcome to the Cows and Bulls Game!\nEnter a 4 digit number: "))
    while len(users_guess) != len(game_number):
        print("The number must be 4 digits")
        users_guess = str(input("Enter a 4 digit number: "))

    guesses += 1

    while users_guess != game_number:
        compare_numbers(users_guess, game_number)
        users_guess = str(input("Enter a 4 digit number: "))
        guesses += 1

    if users_guess == game_number:
        print("\nCongratulations! You have won with ", guesses, " guesses.")


cows_and_bulls()



